experiment_id: exp004
scenario: policy_overhead
repeat: 3
output_dir: results/local/exp004

provider_management_url: http://localhost:19193/management
consumer_management_url: http://localhost:29193/management

provider_protocol_url: http://localhost:19194/protocol
consumer_protocol_url: http://localhost:29194/protocol

provider_public_url: http://localhost:19291/public

api_key: password

request_timeout_s: 30
poll_interval_s: 0.2
poll_timeout_s: 120

policy_mode: no_policy   

asset_template_path: policy/policy-01-policy-enforcement/resources/create-asset.json
contract_definition_template_path: policy/policy-01-policy-enforcement/resources/create-contract-definition.json
dataset_request_template_path: policy/policy-01-policy-enforcement/resources/catalog-requests.json
negotiation_template_path: policy/policy-01-policy-enforcement/resources/contract-request.json

policy_template_simple_path:  policy/policy-01-policy-enforcement/resources/create-policy.json

